name: PyTest Automation Tests with Bdd Structure

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    continue-on-error: true
    strategy:
      matrix:
        python-version: [3.9]
        selenium-version: [4.9.1]
        browser: [headlesschrome]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} with PyTest ${{ matrix.rf-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'    

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Run Appium Server
        uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4


      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: latest
        id: setup-chrome

      - run: |
          echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
          ${{ steps.setup-chrome.outputs.chrome-path }} --version

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip==23.3.1
          pip install -r requirements.txt

      - name: Run Test
        if: always()
        run: pytest ./tests/test_tc01.py
        continue-on-error: true

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./report

      